  
package formularios;

import classes.Dados;
import classes.Produto;
import classes.Utilidades;
//JOptionPane é a ferramenta da "janelinha de erro"
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmClientes extends javax.swing.JInternalFrame {
    private Dados msDados;
    private int proAtual = 0;
    //variável para controle da função de adição de usuários
    private boolean novo  = false;
    //variavel da tabela
    private DefaultTableModel mTabela;
    
    //puxando variável msDados da classe pública Dados
    public void setDados(Dados msDados){
        this.msDados = msDados;
        
    }
    public frmClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fotoPerfil = new javax.swing.JLabel();
        idProduto = new javax.swing.JLabel();
        txtIDProduto = new javax.swing.JTextField();
        descrição = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        preço = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        imposto = new javax.swing.JLabel();
        cmbImposto = new javax.swing.JComboBox<>();
        anotação = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnotacao = new javax.swing.JTextArea();
        btnBuscar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastrar Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        fotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cliente.png"))); // NOI18N

        idProduto.setText("ID Produto:");

        txtIDProduto.setEnabled(false);

        descrição.setText("Descrição:");

        txtDescricao.setEnabled(false);

        preço.setText("Preço:");

        txtPreco.setEnabled(false);

        imposto.setText("Imposto:");

        cmbImposto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "15%" }));
        cmbImposto.setEnabled(false);
        cmbImposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbImpostoActionPerformed(evt);
            }
        });

        anotação.setText("Anotação:");

        txtAnotacao.setColumns(15);
        txtAnotacao.setRows(5);
        jScrollPane2.setViewportView(txtAnotacao);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        btnBuscar.setToolTipText("Busca por um cadastro");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo cadastro.png"))); // NOI18N
        btnNovo.setToolTipText("Adiciona um novo cadastro");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        btnEditar.setToolTipText("Edita o cadastro");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salva o cadastro");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/apagar.png"))); // NOI18N
        btnApagar.setToolTipText("Apaga o cadastro");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancela as alterações");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/primeiro.png"))); // NOI18N
        btnPrimeiro.setToolTipText("Navega para o primeiro cadastro");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anterior.png"))); // NOI18N
        btnAnterior.setToolTipText("Navega para o cadastro anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proximo.png"))); // NOI18N
        btnProximo.setToolTipText("Navega para o próximo cadastro");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ultimo.png"))); // NOI18N
        btnUltimo.setToolTipText("Navega para o último cadastro");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(anotação)
                                    .addComponent(preço))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imposto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(descrição))
                                    .addComponent(idProduto, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIDProduto)
                                    .addComponent(txtDescricao))))
                        .addGap(24, 24, 24)
                        .addComponent(fotoPerfil)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(descrição)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idProduto)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(preço)
                            .addComponent(cmbImposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imposto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anotação)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(fotoPerfil)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        getAccessibleContext().setAccessibleName("Cadastrar Clientes");

        setBounds(0, 0, 476, 537);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        proAtual--;
        if(proAtual == -1){
            proAtual = msDados.numeroProdutos() -1;
        }
        mostrarRegistro();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        proAtual++;
        if(proAtual == msDados.numeroProdutos()){
            proAtual = 0;
        }
        mostrarRegistro();
    }//GEN-LAST:event_btnProximoActionPerformed


    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        //mostra o último usuário do nosso array
        proAtual = msDados.numeroProdutos()-1;
        mostrarRegistro();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        //chama o primeiro usuário do nosso array
        proAtual = 0;
        mostrarRegistro();
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        //setando configuração dos botões da janela para o apertar do botão Novo
        btnPrimeiro.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnProximo.setEnabled(false);
        btnUltimo.setEnabled(false);
        btnNovo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnApagar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        
       //Caixas de textos da janela
        txtIDProduto.setEnabled(true);
        txtPreco.setEnabled(true);
        txtDescricao.setEnabled(true);
        txtAnotacao.setEnabled(true);
        cmbImposto.setEnabled(true);
        
        //limpar caixas de textos
        txtIDProduto.setText("");
        txtPreco.setText("");
        txtDescricao.setText("");
        txtAnotacao.setText("");
        cmbImposto.setSelectedIndex(0);
        
        //variável para controle da função de adição de usuários
        novo = true;
        
        txtIDProduto.requestFocus();
        
        
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //setando configuração dos botões da janela para o apertar do botão Editar
        btnPrimeiro.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnProximo.setEnabled(false);
        btnUltimo.setEnabled(false);
        btnNovo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnApagar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        
       //Caixas de textos da janela
        txtPreco.setEnabled(true);
        txtDescricao.setEnabled(true);
        txtAnotacao.setEnabled(true);
        cmbImposto.setEnabled(true);
        
        //variável para controle da função de adição de usuários
        novo = false;
        
        txtPreco.requestFocus();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane,"deseja deletar este produto?");
                if(resposta !=0){
                    return;
                }
                String msg;
                msg = msDados.deletarProduto(proAtual);
                JOptionPane.showMessageDialog(rootPane, msg);
                proAtual = 0;
                mostrarRegistro();
                preencherTabela();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        //verificação caso o campo ID esteja vazio
        if(txtIDProduto.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor, inserir o número de ID");
            txtIDProduto.requestFocusInWindow();
            return;
        }
        //verificação caso o campo Perfil esteja vazio
        if(cmbImposto.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane,"Favor, selecionar um valor");
            cmbImposto.requestFocusInWindow();
            return;
        }
        //verificação caso o campo preço esteja vazio
        if(txtPreco.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor, Digitar o preço");
            txtPreco.requestFocusInWindow();
            return;
        }
        
        //verificação caso o campo preço seja letras
        if(!Utilidades.isNumeric(txtPreco.getText())){
            JOptionPane.showMessageDialog(rootPane,"Favor, Digitar somente números");
            txtPreco.requestFocusInWindow();
            return;
        }
        
        //verificação caso o campo preço seja a baixo de 0
        int preco = Integer.parseInt(txtPreco.getText());
        if (preco <= 0){ 
            JOptionPane.showMessageDialog(rootPane,"Favor, Digitar números acima de 0");
            txtPreco.requestFocusInWindow();
            return;
        }
        
        //verificação caso o campo Sobrenome esteja vazio
        if(txtDescricao.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Favor, Digitar uma descrição");
            txtDescricao.requestFocusInWindow();
            return;
        }
        
        
        //confirmando se produto já existe (está em laço com a classe pública Dados)
        int pos = msDados.posicaoProduto(txtIDProduto.getText());
        if(novo){
            if(pos!=-1){
                JOptionPane.showMessageDialog(rootPane,"Este produto já existe");
                txtIDProduto.requestFocusInWindow();
                return;
            }
        }else{
            if(pos == -1){
                JOptionPane.showMessageDialog(rootPane,"Este produto ainda não existe");
                txtIDProduto.requestFocusInWindow();
                return;
            }
        }
        
        //Criando um objeto msProduto da classe Produto com os campos que estão dentro do parêntese
        //o objetivo de criar um novo objeto é para gravar as informações de um novo produto
        Produto mProduto = new Produto(txtIDProduto.getText(),
            txtDescricao.getText(),
            preco,
            cmbImposto.getSelectedIndex(),
            txtAnotacao.getText());
        
        String msg;
        if(novo){
            msg = msDados.adicionarProduto(mProduto);
        }else{
            msg = msDados.editarProduto(mProduto, pos);
        }
        JOptionPane.showMessageDialog(rootPane, msg);
        
        //setando configuração dos botões da janela para o apertar do botão Salvar
        btnPrimeiro.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnProximo.setEnabled(true);
        btnUltimo.setEnabled(true);
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(true);
        btnApagar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        //desabilitar as caixas de textos da janela para que sejam inseridas novas informações
        txtIDProduto.setEnabled(false);
        txtPreco.setEnabled(false);
        txtDescricao.setEnabled(false);
        cmbImposto.setEnabled(false);
        txtAnotacao.setEnabled(false);
                
        preencherTabela();
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        //Caixas de textos da janela
        txtIDProduto.setEnabled(false);
        txtPreco.setEnabled(false);
        txtDescricao.setEnabled(false);
        cmbImposto.setEnabled(false);
        txtAnotacao.setEnabled(false);
        
        
        //setando configuração dos botões da janela para o apertar do botão Cancelar
        btnPrimeiro.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnProximo.setEnabled(true);
        btnUltimo.setEnabled(true);
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(true);
        btnApagar.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String produto = JOptionPane.showInputDialog("insira o ID do produto");
        if(produto.equals("")){
            return;
        }
        int pos = msDados.posicaoProduto(produto);
        if(pos == -1){
            JOptionPane.showMessageDialog(rootPane, "Este produto não existe");
            return;
        }
            proAtual = pos;
            mostrarRegistro();
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        //mostra informações de registro do usuário atual na página de cadastro de usuários
        mostrarRegistro();
        preencherTabela();
    }//GEN-LAST:event_formInternalFrameOpened

    private void mostrarRegistro(){
        //código abaixo é o que captura informações de cadastro do produto atual.
        txtIDProduto.setText(msDados.getProdutos()[proAtual].getIdProduto());
        txtDescricao.setText(msDados.getProdutos()[proAtual].getDescricao());
        txtPreco.setText("" + msDados.getProdutos()[proAtual].getPreco());
        txtAnotacao.setText(msDados.getProdutos()[proAtual].getAnotacao());
        cmbImposto.setSelectedIndex(msDados.getProdutos()[proAtual].getImposto());
    }
    
    private void preencherTabela(){
    String titulos [] = {"ID Produto","Descrição", "Preço", "Imposto", "Anotação"};
    String registro[] = new String[5];
    mTabela = new DefaultTableModel(null, titulos);
    for(int i = 0; i< msDados.numeroProdutos(); i++){
        registro[0] = msDados.getProdutos()[i].getIdProduto();
        registro[1] = msDados.getProdutos()[i].getDescricao();
        registro[2] = "" + msDados.getProdutos()[i].getPreco();
        registro[3] = imposto(msDados.getProdutos()[i].getImposto());//adicionado a variável 'imposto' para decidir qual case da combo box será selecionado
        registro[4] = msDados.getProdutos()[i].getAnotacao();


        mTabela.addRow(registro); //também faz parte do código para encaminhar o perfil para a tabela
        }
        tblTabela.setModel(mTabela);
    }   
    //função que troca o valor da variável 'imposto' para decidir qual case da combo box será selecionado
    private String imposto(int idIMPOSTO){
        switch(idIMPOSTO){
            case 0: return "0%";
            case 1: return "10%";
            case 2: return "15%";
            default: return "NÃO DEFINIDO";
        }
    }
    private void cmbImpostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImpostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbImpostoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anotação;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<String> cmbImposto;
    private javax.swing.JLabel descrição;
    private javax.swing.JLabel fotoPerfil;
    private javax.swing.JLabel idProduto;
    private javax.swing.JLabel imposto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel preço;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextArea txtAnotacao;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtIDProduto;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
